export const services = {
  netflix: "Netflix",
  hbo: "HBO Max",
  disney: "Disney+",
  viaplay: "Viaplay",
  prime: "Prime Video",
  apple: "Apple TV",
  tv2: "TV2 PLay",
  filmstriben: "FilmStriben",
};

export const staticMovies = {
  movies: [
    {
      imdb_id: "tt0468569",
      title: "The Dark Knight",
      poster_image: "https://m.media-amazon.com/images/M/MV5BMTIzMDc4MzA2Ml5BMl5BanBnXkFtZTcwODU0MzA3MQ@@._V1_FMjpg_UX510_.jpg?fbclid=IwAR3gDfAz30F6KV8v4bpFB_p-VGiBXqrqT0WAeM8MFxJcjiL8cjFUbQ7mjkE",
      cover_image: "https://m.media-amazon.com/images/M/MV5BMTM1NTcwMTk4OV5BMl5BanBnXkFtZTcwOTczMTk2Mw@@._V1_FMjpg_UX2048_.jpg",
      trailer: "https://www.youtube.com/watch?v=kmJLuwP3MbY",
      runtime: "2h 32min",
      genres: ["Action", "Crime", "Drama"],
      rating: 9.0,
      release_date: "2008-07-18",
      description:
        "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
      language: "English",
      service: [services.hbo],
    },
    {
      imdb_id: "tt0172495",
      title: "Gladiator",
      poster_image:
        "https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UY2599_.jpg?fbclid=IwAR1E1mBvMDTJhaW9p3UsdYKnReS3oc_GfgLopRAxWRJMhxSeUDXzkpnHdd0",
      cover_image: "https://m.media-amazon.com/images/M/MV5BMjE1OTc4MzA0NV5BMl5BanBnXkFtZTcwODQ0NjcxNA@@._V1_FMjpg_UX2048_.jpg",
      trailer: "https://www.youtube.com/watch?v=ol67qo3WhJk",
      runtime: "2h 35min",
      genres: ["Action", "Drama", "Adventure"],
      rating: 8.5,
      release_date: "2000-05-05",
      description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
      language: "English",
      service: [services.prime, services.viaplay],
    },
    {
      imdb_id: "tt0109830",
      title: "Forrest Gump",
      poster_image:
        "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_QL75_UY562_CR4,0,380,562_.jpg?fbclid=IwAR06-d1OvzHfdiLRNmxmdX67jfXfwdv9nfx-D_W71jI8wzMXgsoZRP27ZfE",
      cover_image:
        "https://occ-0-2794-2219.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABSsc41-h_OVZwpZoKKJFiiiQ7hNpl_-Ecm8LXGAlliKCfJb1GFk97igiBg_rYdLPg-LtzEoYAmDmGR-jRGhYNfyjd47J2XNqix9B.jpg?r=9f4",
      trailer: "https://www.youtube.com/watch?v=bLvqoHBptjg",
      runtime: "2h 22min",
      genres: ["Drama", "Romance"],
      rating: 8.8,
      release_date: "1994-07-06",
      description:
        "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
      language: "English",
      service: [services.netflix, services.tv2],
    },
    {
      imdb_id: "tt0361748",
      title: "Inglourious Basterds",
      poster_image: "https://m.media-amazon.com/images/M/MV5BOTJiNDEzOWYtMTVjOC00ZjlmLWE0NGMtZmE1OWVmZDQ2OWJhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_FMjpg_UY3000_.jpg",
      cover_image: "https://m.media-amazon.com/images/M/MV5BMjIxNTE5MjEzM15BMl5BanBnXkFtZTgwMDgyNzk3MTI@._V1_FMjpg_UX1900_.jpg",
      trailer: "https://www.youtube.com/watch?v=KnrRy6kSFF0",
      runtime: "2h 33min",
      genres: ["Adventure", "Drama", "War"],
      rating: 8.3,
      release_date: "2009-08-21",
      description: "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.",
      language: "English, German, French, Italian",
      service: [services.netflix],
    },
    {
      imdb_id: "tt1392190",
      title: "Mad Max: Fury Road",
      poster_image:
        "https://m.media-amazon.com/images/M/MV5BMzUzODU3ZGYtYzQwZS00NmU4LTkwN2QtZWE4N2RjOTY2M2JlXkEyXkFqcGdeQXVyNzI1NzMxNzM@._V1_QL75_UX380_CR0,4,380,562_.jpg?fbclid=IwAR0XpqtfPAhCcJKmMFl1i1D0NOMUQDFsHJ6caC7xVejgYnj3ntx_cM80DR0",
      cover_image: "https://m.media-amazon.com/images/M/MV5BMTgxMDU2OTUzMl5BMl5BanBnXkFtZTgwMDM3NTE2NTE@._V1_FMjpg_UX2048_.jpg",
      trailer: "https://www.youtube.com/watch?v=hEJnMQG9ev8",
      runtime: "2h",
      genres: ["Action", "Adventure", "Sci-Fi"],
      rating: 8.1,
      release_date: "2015-05-15",
      description:
        "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper and a drifter named Max.",
      language: "English",
      service: [services.prime, services.hbo],
    },
    {
      imdb_id: "tt0169547",
      title: "American Beauty",
      poster_image:
        "https://m.media-amazon.com/images/M/MV5BNTBmZWJkNjctNDhiNC00MGE2LWEwOTctZTk5OGVhMWMyNmVhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX675_.jpg?fbclid=IwAR00OzYr4WAQZyyqgtCSW5GVrEU7S66ADEMbXJwHVwpkW8pJH7KtFz24ANs",
      cover_image: "https://m.media-amazon.com/images/M/MV5BMTYzNjIwNzI0OV5BMl5BanBnXkFtZTcwNjIyODY3Mw@@._V1_FMjpg_UX2048_.jpg",
      trailer: "https://www.youtube.com/watch?v=3Fzsq35aFTw",
      runtime: "2h 2min",
      genres: ["Drama"],
      rating: 8.3,
      release_date: "1999-10-01",
      description: "A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter's best friend.",
      language: "English",
      service: [services.tv2],
    },
    {
      imdb_id: "tt0076759",
      title: "Star Wars: Episode IV - A New Hope",
      poster_image:
        "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_QL75_UX380_CR0,9,380,562_.jpg?fbclid=IwAR2WWUoUcEibH_jwAvNyQIQ8bUBi2aYOaHOU0FrrdVmHCiYAkNjevcM9WtU",
      cover_image: "https://m.media-amazon.com/images/M/MV5BMTk3MTkzNTk3Ml5BMl5BanBnXkFtZTgwOTcyMzQyNDM@._V1_FMjpg_UX2048_.jpg",
      trailer: "https://www.youtube.com/watch?v=1g3_CFmnU7k",
      runtime: "2h 1min",
      genres: ["Action", "Adventure", "Fantasy"],
      rating: 8.6,
      release_date: "1977-05-25",
      description:
        "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.",
      language: "English",
      service: [services.viaplay, services.disney],
    },
    {
      imdb_id: "tt6751668",
      title: "Parasite",
      poster_image: "https://m.media-amazon.com/images/M/MV5BMTE5MGYwMWUtMWVmYi00MmYyLWI1OTYtNWUwZTZmOTY0MmIxXkEyXkFqcGdeQXVyMTAyOTE2ODg0._V1_FMjpg_UX1123_.jpg",
      cover_image: "https://m.media-amazon.com/images/M/MV5BNGNmOTNlMzItNzJjYi00MTM4LWIyYzktOGRlOTY1NzQ5MjFhXkEyXkFqcGdeQXVyODUzMDY0NTE@._V1_FMjpg_UX2048_.jpg",
      trailer: "https://www.youtube.com/watch?v=5xH0HfJHsaY",
      runtime: "2h 12min",
      genres: ["Comedy", "Drama", "Thriller"],
      rating: 8.6,
      release_date: "2019-11-08",
      description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
      language: "Korean",
      service: [services.filmstriben],
    },
    {
      imdb_id: "tt0167260",
      title: "The Lord of the Rings: The Return of the King",
      poster_image:
        "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX800_.jpg?fbclid=IwAR0U3ptAmfumVD3C3gVtGYPwMEzfmPAUg_h90iYG5ccB6UVXvAdTsLY0vDE",
      cover_image: "https://m.media-amazon.com/images/M/MV5BMTk1ODY0NDg2M15BMl5BanBnXkFtZTcwNTU2MTk2Mw@@._V1_FMjpg_UX2048_.jpg",
      trailer: "https://www.youtube.com/watch?v=r5X-hFf6Bwo",
      runtime: "3h 21min",
      genres: ["Action", "Adventure", "Drama"],
      rating: 8.9,
      release_date: "2003-12-17",
      description: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
      language: "English",
      service: [services.prime, services.hbo],
    },
    {
      imdb_id: "tt0111161",
      title: "The Shawshank Redemption",
      poster_image:
        "https://m.media-amazon.com/images/M/MV5BMzBmNWM0YzktOTM2MC00MzVkLWFiNjUtNWVjMWRiOTQ0OWM0XkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_FMjpg_UY3000_.jpg?fbclid=IwAR2DrnpSSMzQ_78UJfifFBp4MX9b_OFL59pUqhdOcakWzGXTK74rJKArmoc",
      cover_image: "https://m.media-amazon.com/images/M/MV5BMTgxMTU1MDkwOV5BMl5BanBnXkFtZTcwMDQxNDY3Mw@@._V1_FMjpg_UX1800_.jpg",
      trailer: "https://www.youtube.com/watch?v=6hB3S9bIaco",
      runtime: "2h 22min",
      genres: ["Drama", "Crime"],
      rating: 9.3,
      release_date: "1994-10-14",
      description: "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.",
      language: "English",
      service: [services.prime, services.viaplay, services.filmstriben],
    },
    {
      imdb_id: "tt0110912",
      title: "Pulp Fiction",
      poster_image: "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1055_.jpg",
      cover_image: "https://m.media-amazon.com/images/M/MV5BMjE1ODYxOTkxOF5BMl5BanBnXkFtZTgwNTE4OTEwMjE@._V1_FMjpg_UX1600_.jpg",
      trailer: "https://www.youtube.com/watch?v=s7EdQ4FqbhY",
      runtime: "2h 34min",
      genres: ["Crime", "Drama"],
      rating: 8.9,
      release_date: "1994-10-14",
      description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
      language: "English",
      service: [services.viaplay],
    },
    {
      imdb_id: "tt2488496",
      title: "Star Wars: The Force Awakens",
      poster_image: "https://m.media-amazon.com/images/M/MV5BOTAzODEzNDAzMl5BMl5BanBnXkFtZTgwMDU1MTgzNzE@._V1_FMjpg_UY3240_.jpg",
      cover_image: "https://m.media-amazon.com/images/M/MV5BMDMzODA1MzAtM2ZhYS00OGM5LTgxNDUtZTE0NDcyMTY0ZGM3XkEyXkFqcGdeQXVyNDczOTA3ODE@._V1_FMjpg_UX2160_.jpg",
      trailer: "https://www.youtube.com/watch?v=sGbxmsDFVnE",
      runtime: "2h 18min",
      genres: ["Action", "Adventure", "Fantasy"],
      rating: 7.8,
      release_date: "2015-12-18",
      description: "As a new threat to the galaxy rises, Rey, a desert scavenger, and Finn, an ex-stormtrooper, must join Han Solo and Chewbacca to search for the one hope of restoring peace.",
      language: "English",
      service: [services.disney],
    },
    {
      imdb_id: "tt1375666",
      title: "Inception",
      poster_image: "https://m.media-amazon.com/images/M/MV5BMTk4NzE0OTQxMV5BMl5BanBnXkFtZTcwOTE0MjYwMw@@._V1_FMjpg_UX550_.jpg?fbclid=IwAR1GAxFiE9zdvRoo_A8-ZEdRsI3HFE_LRgNgos_nSk2kJGIZ04CozKvExNU",
      cover_image: "https://m.media-amazon.com/images/M/MV5BNjMxNjI1Mjc1OV5BMl5BanBnXkFtZTcwMDY0OTk1Mw@@._V1_FMjpg_UX2048_.jpg",
      trailer: "https://www.youtube.com/watch?v=YoHD9XEInc0",
      runtime: "2h 28min",
      genres: ["Action", "Adventure", "Sci-Fi"],
      rating: 8.8,
      release_date: "2010-07-16",
      description:
        "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
      language: "English",
      service: [services.prime, services.viaplay, services.hbo],
    },
    {
      imdb_id: "tt4154796",
      title: "Avengers: Endgame",
      poster_image: "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_FMjpg_UY2048_.jpg",
      cover_image: "https://m.media-amazon.com/images/M/MV5BZGFmYWU1OGUtYmUxNS00N2E4LTkxYmMtZGYxM2NmYzhjZjJkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_FMjpg_UX2048_.jpg",
      trailer: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
      runtime: "3h 1min",
      genres: ["Action", "Adventure", "Sci-Fi"],
      rating: 8.4,
      release_date: "2019-04-26",
      description:
        "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
      language: "English",
      service: [services.disney],
    },
  ],
};
